### ISSUE TITLE
収支ごとの一覧に検索・ページネーションをいれる

### ISSUE THREAD

**Issue by nakatomoyanyan** [nakatomoyanyan/household_account_book#11]
* 機能概要
  * 収支ごとの一覧で何年、何月を指定して、その範囲のデータを取得して一覧で表示
  * 収支ごとの一覧でページネーションを追加(1ページにつき5件ずつ表示)
  * seedであらかじめ収入、支出のデータを用意しておく
  * 年、月の選択はプルダウンメニュー(DBに収入or支出が登録されている年と月を表示)
  * 検索ボタンを押すと一覧が表示される
* 画面イメージ  (画像は収入画面の場合。支出画面も同様な感じ)
![一覧_検索_ページネーション](https://github.com/user-attachments/assets/a3e53729-2255-4433-8162-f5cad44e3ee2)

**Comment by SaitoJP** [comment]
- 質問
  - 1ページ5件ずつの理由は何でしょうか？（50件くらいだしてもいいかと思いましたが）
  - 日付のデフォルトソート順についてですが、現在は昇順ですかね。一般的なサービスだと降順が多いかと思いますが、なにか意図がありますか？
- 提案
  - 各列にソート機能を追加してはどうでしょうか？ ransackなら簡単にできますし、このようなデータテーブルには一般的にソート機能がついてますね。
  - 項目をキーワード検索できるようにしたら便利かと思いますがどうでしょう？
  - 検索結果一覧に表示されたものの収入合計が画面に表示されたら便利かも（思いつき）

**Comment by iwaguma-manabi** [comment]
> 画面イメージ (画像は収入画面の場合。支出画面も同様な感じ)

指定年月の収入と支出を同時に検索したいという需要はない感じでしょうか？
これくらいなら別の画面に分けずに「収入/支出」列を増やして検索条件に追加したら２つに分ける場合と同じことができつつ、追加で同時に見る使い方もできるかなと思いました。

**Comment by nakatomoyanyan** [comment]
@SaitoJP 
コメントありがとうございます。
> 1ページ5件ずつの理由は何でしょうか？（50件くらいだしてもいいかと思いましたが）

理由は画面が縦に長くなりすぎないようにしたいと考えていたからです。考えてみればたしかに50件ぐらい表示しても問題ないですね。

> 日付のデフォルトソート順についてですが、現在は昇順ですかね。一般的なサービスだと降順が多いかと思いますが、なにか意図がありますか？

意図は特になかったです。日付のソート順を降順にします。ご指摘ありがとうございます。

> 各列にソート機能を追加してはどうでしょうか？ ransackなら簡単にできますし、このようなデータテーブルには一般的にソート機能がついてますね。
項目をキーワード検索できるようにしたら便利かと思いますがどうでしょう？
検索結果一覧に表示されたものの収入合計が画面に表示されたら便利かも（思いつき）

提案ありがとうございます。
各列のソート機能、項目のキーワード検索、検索結果一覧に表示されたものの合計の表示機能を実装したいと思います。

**Comment by nakatomoyanyan** [comment]
@iwaguma-manabi 
コメントありがとうございます。

> 指定年月の収入と支出を同時に検索したいという需要はない感じでしょうか？
これくらいなら別の画面に分けずに「収入/支出」列を増やして検索条件に追加したら２つに分ける場合と同じことができつつ、追加で同時に見る使い方もできるかなと思いました。

たしかに指定年月の収入と支出を同時に検索できると便利ですね。
その場合、支出の収入の検索結果をイメージのように右と左の列に分けて表示するのはどうでしょうか？

* イメージ

![一覧_検索_ページネーション_2](https://github.com/user-attachments/assets/22ef35f5-4d09-4e80-adf7-53562d2302c5)

**Comment by iwaguma-manabi** [comment]
> 支出の収入の検索結果を右と左の列に分けて表示するのはどうでしょうか？

仮にページング5件で3件/2件だとそれぞれ配分する感じですかね。

### 収入だけまたは支出だけを調べたい時にはデッドスペースになる

ただしそれを許容するなら問題なし。
例えばユーザーの操作を減らしたいので検索切り替え自体をさせないため等
例えば収入だけまたは支出だけでもう片方が不要な需要は薄いので両方出す前提等

### 配分は分かりやすくなるが時系列情報はやや損なう

例えば「支出抑え」「給料日」「支出緩む」みたいな情報は双方が混ざって日付順で縦並びのほうが読み取りやすい。

配分優先という意図で作る、または、左右に分けた際に各上詰めではなく時系列表現もあると分かりやすいかも。

```
　　     収入 　　　支出
10/2   〇〇
10/3            □□
```

**Comment by nakatomoyanyan** [comment]
コメントありがとうございます。
支出、収入を右左で分けずに表示しようと思います。
* 理由
  * 収入だけまたは支出だけを調べたい時にはデッドスペースになるから
  * 時系列情報を読み取りやすいほうが家計を分析しやすいから
  * ソート機能を使えば支出、収入だけの情報を分けて取得できるから

**Comment by nakatomoyanyan** [comment]
議論の内容を踏まえた実装内容をまとめました。
ご確認のほどよろしくお願いいたします。
* 機能概要
  * 何年、何月、(収入だけ、支出だけ、両方)、名目(例：給料、食費、すべてetc)を指定して、その範囲のデータを取得して一覧で表示
  * ページネーションを追加(1ページにつき50件ずつ表示)
  * seedであらかじめ収入、支出のデータを用意しておく
  * 年、月の選択はプルダウンメニュー(DBに収入or支出が登録されている年と月を表示)
  * 検索ボタンを押すと一覧が表示される
  * 支出、収入を右左で分けずに表示
  * 日付のソート順を降順にする
  * 各列にソート機能を追加(ransackを使用)
  * 検索結果一覧に表示されたものの合計を表示
* 画面イメージ(収入画面と支出画面に同じものを実装)
 
![一覧_検索_ページネーション_3](https://github.com/user-attachments/assets/a8215fbe-bd5b-469b-85bc-7160e678a8cb)

**Comment by nakatomoyanyan** [comment]
あとから考えて検索機能付きの一覧はhome画面のsummaryの下部に実装することにしました。
理由は収入と支出をどちらも検索できる仕様にするので、home画面に実装したほうが責務が明確になると考えたからです。
支出画面、収入画面の一覧表示はそのままにします。
